# Configuración de DigitalOcean App Platform para Productos Backend
# Este archivo define cómo se desplegará la aplicación en App Platform

name: productos-backend
region: nyc

# Servicios de la aplicación
services:
  - name: productos-api
    # Configuración de build desde Dockerfile
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: modicl/productos-backend
      branch: main
      deploy_on_push: true
    
    # Configuración de recursos
    instance_size_slug: basic-xxs  # 512MB RAM, 0.5 vCPU - Ajustar según necesidad
    instance_count: 1
    
    # Healthcheck
    health_check:
      http_path: /actuator/health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Configuración HTTP
    http_port: 8080
    
    # Variables de entorno
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
      
      - key: SERVER_PORT
        value: "8080"
      
      # Database URL - IMPORTANTE: Configurar en App Platform Console
      - key: DB_URL
        value: "${db.DATABASE_URL}"
        type: SECRET
      
      - key: DB_USERNAME
        value: "${db.USERNAME}"
        type: SECRET
      
      - key: DB_PASSWORD
        value: "${db.PASSWORD}"
        type: SECRET
      
      # JWT Secret - IMPORTANTE: Debe ser el mismo que el microservicio de usuarios
      - key: JWT_SECRET
        value: "profesorsaavedraporfavorpongame-un-7-en-el-examenporfavorgracias"
        type: SECRET
      
      - key: JWT_EXPIRATION
        value: "86400000"
      
      # Java Options para optimización de memoria
      - key: JAVA_OPTS
        value: "-Xmx400m -Xms256m -XX:+UseG1GC -XX:MaxGCPauseMillis=100"
    
    # Rutas públicas
    routes:
      - path: /

# Base de datos (opcional - si usas database managed de DO)
# databases:
#   - name: productos-db
#     engine: PG
#     version: "18"
#     size: db-s-1vcpu-1gb
#     num_nodes: 1

# Dominios personalizados (opcional)
# domains:
#   - domain: api.huertohogar.cl
#     type: PRIMARY
